%% -*- erlang -*-
IsRebar3 = erlang:function_exported(rebar3, main, 1),

Rebar2Deps =
  [
   {local, ".*", {git, "https://github.com/sile/local.git", {tag, "0.2.1"}}},
   {passage, ".*", {git, "https://github.com/sile/passage.git", {tag, "0.2.6"}}},
   {thrift_protocol, ".*", {git, "https://github.com/sile/thrift_protocol.git", {tag, "0.1.5"}}}
  ],

case IsRebar3 of
    true  -> CONFIG;
    false -> lists:keyreplace(deps, 1, CONFIG, {deps, Rebar2Deps})
end.
